// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: veya.proto

package eu.over9000.veya.proto;

@SuppressWarnings("ALL")
public final class ProtoDefinitions {
  private ProtoDefinitions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChunkStackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkStack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> 
        getChunkList();
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk getChunk(int index);
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    int getChunkCount();
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    java.util.List<? extends eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder> 
        getChunkOrBuilderList();
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder getChunkOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ChunkStack}
   */
  public static final class ChunkStack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChunkStack)
      ChunkStackOrBuilder {
    // Use ChunkStack.newBuilder() to construct.
    private ChunkStack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChunkStack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChunkStack defaultInstance;
    public static ChunkStack getDefaultInstance() {
      return defaultInstance;
    }

    public ChunkStack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkStack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                chunk_ = new java.util.ArrayList<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk>();
                mutable_bitField0_ |= 0x00000001;
              }
              chunk_.add(input.readMessage(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          chunk_ = java.util.Collections.unmodifiableList(chunk_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.class, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Builder.class);
    }

    public static com.google.protobuf.Parser<ChunkStack> PARSER =
        new com.google.protobuf.AbstractParser<ChunkStack>() {
      public ChunkStack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkStack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkStack> getParserForType() {
      return PARSER;
    }

    public interface ChunkOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ChunkStack.Chunk)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 y = 1;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 1;</code>
       */
      int getY();

      /**
       * <code>required bytes data = 2;</code>
       */
      boolean hasData();
      /**
       * <code>required bytes data = 2;</code>
       */
      com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code ChunkStack.Chunk}
     */
    public static final class Chunk extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ChunkStack.Chunk)
        ChunkOrBuilder {
      // Use Chunk.newBuilder() to construct.
      private Chunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Chunk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Chunk defaultInstance;
      public static Chunk getDefaultInstance() {
        return defaultInstance;
      }

      public Chunk getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Chunk(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                y_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                data_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_Chunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_Chunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.class, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder.class);
      }

      public static com.google.protobuf.Parser<Chunk> PARSER =
          new com.google.protobuf.AbstractParser<Chunk>() {
        public Chunk parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Chunk(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Chunk> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int Y_FIELD_NUMBER = 1;
      private int y_;
      /**
       * <code>required int32 y = 1;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 y = 1;</code>
       */
      public int getY() {
        return y_;
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      private void initFields() {
        y_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasData()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, y_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, data_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, y_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, data_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ChunkStack.Chunk}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ChunkStack.Chunk)
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_Chunk_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_Chunk_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.class, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder.class);
        }

        // Construct using eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_Chunk_descriptor;
        }

        public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk getDefaultInstanceForType() {
          return eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.getDefaultInstance();
        }

        public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk build() {
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk buildPartial() {
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk result = new eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk) {
            return mergeFrom((eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk other) {
          if (other == eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.getDefaultInstance()) return this;
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasData()) {
            setData(other.getData());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasY()) {
            
            return false;
          }
          if (!hasData()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int y_ ;
        /**
         * <code>required int32 y = 1;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 y = 1;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 1;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000001;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 1;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes data = 2;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes data = 2;</code>
         */
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>required bytes data = 2;</code>
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes data = 2;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000002);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ChunkStack.Chunk)
      }

      static {
        defaultInstance = new Chunk(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ChunkStack.Chunk)
    }

    public static final int CHUNK_FIELD_NUMBER = 1;
    private java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> chunk_;
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    public java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> getChunkList() {
      return chunk_;
    }
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    public java.util.List<? extends eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder> 
        getChunkOrBuilderList() {
      return chunk_;
    }
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    public int getChunkCount() {
      return chunk_.size();
    }
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk getChunk(int index) {
      return chunk_.get(index);
    }
    /**
     * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
     */
    public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder getChunkOrBuilder(
        int index) {
      return chunk_.get(index);
    }

    private void initFields() {
      chunk_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getChunkCount(); i++) {
        if (!getChunk(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < chunk_.size(); i++) {
        output.writeMessage(1, chunk_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < chunk_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, chunk_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkStack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkStack)
        eu.over9000.veya.proto.ProtoDefinitions.ChunkStackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.class, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Builder.class);
      }

      // Construct using eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChunkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (chunkBuilder_ == null) {
          chunk_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          chunkBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.over9000.veya.proto.ProtoDefinitions.internal_static_ChunkStack_descriptor;
      }

      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack getDefaultInstanceForType() {
        return eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.getDefaultInstance();
      }

      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack build() {
        eu.over9000.veya.proto.ProtoDefinitions.ChunkStack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack buildPartial() {
        eu.over9000.veya.proto.ProtoDefinitions.ChunkStack result = new eu.over9000.veya.proto.ProtoDefinitions.ChunkStack(this);
        int from_bitField0_ = bitField0_;
        if (chunkBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            chunk_ = java.util.Collections.unmodifiableList(chunk_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.chunk_ = chunk_;
        } else {
          result.chunk_ = chunkBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.over9000.veya.proto.ProtoDefinitions.ChunkStack) {
          return mergeFrom((eu.over9000.veya.proto.ProtoDefinitions.ChunkStack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack other) {
        if (other == eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.getDefaultInstance()) return this;
        if (chunkBuilder_ == null) {
          if (!other.chunk_.isEmpty()) {
            if (chunk_.isEmpty()) {
              chunk_ = other.chunk_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChunkIsMutable();
              chunk_.addAll(other.chunk_);
            }
            onChanged();
          }
        } else {
          if (!other.chunk_.isEmpty()) {
            if (chunkBuilder_.isEmpty()) {
              chunkBuilder_.dispose();
              chunkBuilder_ = null;
              chunk_ = other.chunk_;
              bitField0_ = (bitField0_ & ~0x00000001);
              chunkBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChunkFieldBuilder() : null;
            } else {
              chunkBuilder_.addAllMessages(other.chunk_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getChunkCount(); i++) {
          if (!getChunk(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.over9000.veya.proto.ProtoDefinitions.ChunkStack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.over9000.veya.proto.ProtoDefinitions.ChunkStack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> chunk_ =
        java.util.Collections.emptyList();
      private void ensureChunkIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          chunk_ = new java.util.ArrayList<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk>(chunk_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder> chunkBuilder_;

      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> getChunkList() {
        if (chunkBuilder_ == null) {
          return java.util.Collections.unmodifiableList(chunk_);
        } else {
          return chunkBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public int getChunkCount() {
        if (chunkBuilder_ == null) {
          return chunk_.size();
        } else {
          return chunkBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk getChunk(int index) {
        if (chunkBuilder_ == null) {
          return chunk_.get(index);
        } else {
          return chunkBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder setChunk(
          int index, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.set(index, value);
          onChanged();
        } else {
          chunkBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder setChunk(
          int index, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.set(index, builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder addChunk(eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.add(value);
          onChanged();
        } else {
          chunkBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder addChunk(
          int index, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.add(index, value);
          onChanged();
        } else {
          chunkBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder addChunk(
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.add(builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder addChunk(
          int index, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.add(index, builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder addAllChunk(
          java.lang.Iterable<? extends eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk> values) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, chunk_);
          onChanged();
        } else {
          chunkBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder clearChunk() {
        if (chunkBuilder_ == null) {
          chunk_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          chunkBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public Builder removeChunk(int index) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.remove(index);
          onChanged();
        } else {
          chunkBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder getChunkBuilder(
          int index) {
        return getChunkFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder getChunkOrBuilder(
          int index) {
        if (chunkBuilder_ == null) {
          return chunk_.get(index);  } else {
          return chunkBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public java.util.List<? extends eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder> 
           getChunkOrBuilderList() {
        if (chunkBuilder_ != null) {
          return chunkBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(chunk_);
        }
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder addChunkBuilder() {
        return getChunkFieldBuilder().addBuilder(
            eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.getDefaultInstance());
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder addChunkBuilder(
          int index) {
        return getChunkFieldBuilder().addBuilder(
            index, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.getDefaultInstance());
      }
      /**
       * <code>repeated .ChunkStack.Chunk chunk = 1;</code>
       */
      public java.util.List<eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder> 
           getChunkBuilderList() {
        return getChunkFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder> 
          getChunkFieldBuilder() {
        if (chunkBuilder_ == null) {
          chunkBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.Chunk.Builder, eu.over9000.veya.proto.ProtoDefinitions.ChunkStack.ChunkOrBuilder>(
                  chunk_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          chunk_ = null;
        }
        return chunkBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ChunkStack)
    }

    static {
      defaultInstance = new ChunkStack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ChunkStack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkStack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChunkStack_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkStack_Chunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChunkStack_Chunk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nveya.proto\"P\n\nChunkStack\022 \n\005chunk\030\001 \003(" +
      "\0132\021.ChunkStack.Chunk\032 \n\005Chunk\022\t\n\001y\030\001 \002(\005" +
      "\022\014\n\004data\030\002 \002(\014B*\n\026eu.over9000.veya.proto" +
      "B\020ProtoDefinitions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChunkStack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChunkStack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChunkStack_descriptor,
        new java.lang.String[] { "Chunk", });
    internal_static_ChunkStack_Chunk_descriptor =
      internal_static_ChunkStack_descriptor.getNestedTypes().get(0);
    internal_static_ChunkStack_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChunkStack_Chunk_descriptor,
        new java.lang.String[] { "Y", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
